name: Build and deploy ASP.Net Core app to Azure Web App - API-TASK-MANAGER1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # FIX 1: Apuntamos 'publish' directamente a tu proyecto de API.
      # 'publish' ya hace un 'build', así que combinamos los pasos.
      - name: dotnet publish
        run: dotnet publish ./TaskManager.API/TaskManager.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        # NOTA: Si tu archivo .csproj no está en una carpeta 'TaskManager.API', 
        # ajusta la ruta (ej. 'TaskManager.API.csproj')

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # FIX 2: Se corrigió la indentación de este paso.
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6AB70E2DE730488F9082E280A0B64FCA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97DEBD9AC6304A08B95C8722E3178B42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D3EE594482148DF94166328EF67F257 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'API-TASK-MANAGER1'
          slot-name: 'Production'
          package: . # El 'package: .' está bien porque estamos en el directorio de 'deploy'
